export const NEW_PICKUP_REQUEST = "NEW_PICKUP_REQUEST";
export const NEW_PICKUP_SUCCESS = "NEW_PICKUP_SUCCESS";
export const NEW_PICKUP_RESET = "NEW_PICKUP_RESET";
export const NEW_PICKUP_FAIL = "NEW_PICKUP_FAIL";

export const ADMIN_PICKUP_REQUEST = "ADMIN_PICKUP_REQUEST";
export const ADMIN_PICKUP_SUCCESS = "ADMIN_PICKUP_SUCCESS";
export const ADMIN_PICKUP_FAIL = "ADMIN_PICKUP_FAIL";

export const UPDATE_PICKUP_REQUEST = "UPDATE_PICKUP_REQUEST";
export const UPDATE_PICKUP_SUCCESS = "UPDATE_PICKUP_SUCCESS";
export const UPDATE_PICKUP_RESET = "UPDATE_PICKUP_RESET";
export const UPDATE_PICKUP_FAIL = "UPDATE_PICKUP_FAIL";

export const DELETE_PICKUP_REQUEST = "DELETE_PICKUP_REQUEST";
export const DELETE_PICKUP_SUCCESS = "DELETE_PICKUP_SUCCESS";
export const DELETE_PICKUP_RESET = "DELETE_PICKUP_RESET";
export const DELETE_PICKUP_FAIL = "DELETE_PICKUP_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";