export const NEW_PICKUP_REQUEST = "NEW_PICKUP_REQUEST";
export const NEW_PICKUP_SUCCESS = "NEW_PICKUP_SUCCESS";
export const NEW_PICKUP_RESET = "NEW_PICKUP_RESET";
export const NEW_PICKUP_FAIL = "NEW_PICKUP_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";